name: Setup a Go
on:  
  push:
  pull_request:
  schedule:
  - cron: "*/5 * * * *"
jobs:
 setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1.11]
         flag: [A]
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .
    - name: Setup a Go
      run: |
          echo "sudo apt update"
